INSERT INTO stockwatcher.Exchange (exchange_id, exchange_name, active, currency_code) VALUES ('AMEX','American Stock Exchange', true, 'USD');
INSERT INTO stockwatcher.Exchange (exchange_id, exchange_name, active, currency_code) VALUES ('NASDAQ','NASDAQ Stock Exchange', true, 'USD');
INSERT INTO stockwatcher.Exchange (exchange_id, exchange_name, active, currency_code) VALUES ('NYSE','New York Stock Exchange', true, 'USD');
