INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (1,'Basic Materials');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (2,'Conglomerates');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (3,'Consumer Goods');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (4,'Financial');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (5,'Healthcare');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (6,'Industrial Goods');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (7,'Services');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (8,'Technology');
INSERT INTO stockwatcher.Sector (sector_id, sector_name) VALUES (9,'Utilities');
