apiVersion: v1
kind: Pod
metadata:
  name: universal-test-client
spec:
  containers:
  - name: busybox
    image: docker.io/busybox:latest
    command:
    - top
    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        cpu: 100m
        memory: 512M
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL